name: Test Artifact Upload

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  actions: read

jobs:
  test-artifact-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create test file
        run: echo "This is a test artifact." > test_output.txt

      - name: Upload test artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-artifact
          path: test_output.txt
